In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import math
import seaborn as sns
import pandas as pd
import os
import matplotlib.pyplot as plt

In [ ]:
from pathlib import Path

input_folder = '/content/gdrive/MyDrive/Colab Notebooks/201020_TestData'
raw_data_dir = Path(input_folder)
excel_files = raw_data_dir.glob('20201020_*')

for excel_file in excel_files:
  print(excel_file)

/content/gdrive/MyDrive/Colab Notebooks/201020_TestData/20201020_1_1P_UC_WT.xlsx
/content/gdrive/MyDrive/Colab Notebooks/201020_TestData/20201020_2.1_1P_N.xlsx
/content/gdrive/MyDrive/Colab Notebooks/201020_TestData/20201020_2.2_1P_BT.xlsx
/content/gdrive/MyDrive/Colab Notebooks/201020_TestData/20201020_2.3_1P_N.xlsx
/content/gdrive/MyDrive/Colab Notebooks/201020_TestData/20201020_3.1_1P_BT.xlsx
/content/gdrive/MyDrive/Colab Notebooks/201020_TestData/20201020_3.2_1P_N.xlsx
/content/gdrive/MyDrive/Colab Notebooks/201020_TestData/20201020_4.1_1P_BT.xlsx
/content/gdrive/MyDrive/Colab Notebooks/201020_TestData/20201020_4.2_1P_BT.xlsx
/content/gdrive/MyDrive/Colab Notebooks/201020_TestData/20201020_6.1_1P_UC_WT.xlsx
/content/gdrive/MyDrive/Colab Notebooks/201020_TestData/20201020_5.1_1P_UC_WT.xlsx
/content/gdrive/MyDrive/Colab Notebooks/201020_TestData/20201020_6.2_1P_N.xlsx
/content/gdrive/MyDrive/Colab Notebooks/201020_TestData/20201020_5.2_1P_N.xlsx


In [ ]:
import pandas as pd
from pathlib import Path

input_folder = '/content/gdrive/MyDrive/Colab Notebooks/201020_TestData'
raw_data_dir = Path(input_folder)
excel_files = raw_data_dir.glob('20201020_*')

total_df = pd.DataFrame()

for excel_file in excel_files:
  df = pd.read_excel(excel_file)
  total_df = total_df.append(df, ignore_index = True)

total_df

용접속도  송급속도  전압보정  위빙(hz)  위빙(좌)  ...  기공  용락  오버랩  용접선 이탈 (벽)  용접선 이탈
0        32   9.0  -2.5       2    0.3  ... NaN NaN  NaN         NaN     NaN
1        32   9.0  -2.5       2    0.3  ... NaN NaN  NaN         NaN     NaN
2        32   9.0  -2.5       2    0.3  ... NaN NaN  NaN         NaN     NaN
3        32   9.0  -2.5       2    0.3  ... NaN NaN  NaN         NaN     NaN
4        32   9.0  -2.5       2    0.3  ... NaN NaN  NaN         NaN     NaN
...     ...   ...   ...     ...    ...  ...  ..  ..  ...         ...     ...
45571    35   9.5  -3.0       2    0.3  ... NaN NaN  NaN         NaN     NaN
45572    35   9.5  -3.0       2    0.3  ... NaN NaN  NaN         NaN     NaN
45573    35   9.5  -3.0       2    0.3  ... NaN NaN  NaN         NaN     NaN
45574    35   9.5  -3.0       2    0.3  ... NaN NaN  NaN         NaN     NaN
45575    35   9.5  -3.0       2    0.3  ... NaN NaN  NaN         NaN     NaN

[45576 rows x 29 columns]

In [ ]:
folder = '/content/gdrive/MyDrive/Colab Notebooks/201020_TestData/'
merged_excel_file = folder + 'all_data.xlsx'

total_df.to_excel(merged_excel_file, sheet_name='all_data', index = False)

print("생성파일:", merged_excel_file)

생성파일: /content/gdrive/MyDrive/Colab Notebooks/201020_TestData/all_data.xlsx


In [ ]:
import pandas as pd
from pandas import DataFrame
from pandas import Series
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
plt.rcParams['figure.figsize'] = [10,6]
%matplotlib inline

In [ ]:
data = pd.read_excel('/content/gdrive/MyDrive/Colab Notebooks/201020_TestData/all_data.xlsx')
data.head()

용접속도  송급속도  전압보정  위빙(hz)  위빙(좌)  위빙(우)  ...  언더컷  기공  용락  오버랩  용접선 이탈 (벽)  용접선 이탈
0    32   9.0  -2.5       2    0.3    0.3  ...  NaN NaN NaN  NaN         NaN     NaN
1    32   9.0  -2.5       2    0.3    0.3  ...  NaN NaN NaN  NaN         NaN     NaN
2    32   9.0  -2.5       2    0.3    0.3  ...  NaN NaN NaN  NaN         NaN     NaN
3    32   9.0  -2.5       2    0.3    0.3  ...  NaN NaN NaN  NaN         NaN     NaN
4    32   9.0  -2.5       2    0.3    0.3  ...  NaN NaN NaN  NaN         NaN     NaN

[5 rows x 29 columns]

In [ ]:
#excel_original: 모든 파일 통합 데이터
excel=data.drop(['Unnamed: 6','Unnamed: 14','Unnamed: 19','용접선 이탈 (벽)','용접선 이탈'],axis=1)#고려필요 없음(read_me)
excel=excel.drop(['용접속도','송급속도','전압보정','위빙(hz)','위빙(좌)','위빙(우)'],axis=1)#고려필요 없음(read_me) 질문필요
excel=excel.drop(excel[(excel['Start']==1.0)|(excel['End']==1.0)].index)#Start, End에 해당=> 제거(read_me)
excel=excel.drop(['Start','End'],axis=1)
excel=excel.drop(['Pass','형상','두께(1)','두께(2)'],axis=1)#다 일정한 값을 가짐
excel=excel.drop(['WIRESPEED','WINDSPEED','WINDANGLE'],axis=1)#read_me 조건에서 처리 질문필요

In [ ]:
print(excel.isnull().sum())
print(sum(excel.isnull().sum(axis=1)==4))

WELDTIME        0
CURRENT         0
VOLTAGE         0
GAS             0
정상          15447
언더컷         33728
기공          41747
용락          34320
오버랩         41747
dtype: int64
41746


In [ ]:
conditionlist = [
  (excel['정상'] ==1) ,
  (excel['용락'] ==1) ,
  (excel['오버랩'] ==1) ]
choicelist = [1, 2, 3]
excel['label'] = np.select(conditionlist, choicelist, default=-1)

In [ ]:
excel=excel.drop(['정상','언더컷','기공','용락','오버랩'],axis=1)
excel

WELDTIME  CURRENT  VOLTAGE   GAS  label
304        3.05    407.6     34.0  26.9      1
305        3.06    428.0     34.9  26.9      1
306        3.07    409.8     34.6  26.8      1
307        3.08    421.3     35.0  26.7      1
308        3.09    376.1     35.2  26.7      1
...         ...      ...      ...   ...    ...
45374     37.41    468.1     29.0  23.2      1
45375     37.42    370.3     29.5  23.2      1
45376     37.43    392.0     29.4  23.2      1
45377     37.44    409.5     29.1  23.2      1
45378     37.45    336.9     28.4  23.1      1

[41747 rows x 5 columns]

In [ ]:
#데이터셋 분리
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X = excel.iloc[:, :-1].values
y = excel.iloc[:, 4].values
X_train, X_test, y_train, y_test = train_test_split(X, y,  test_size=0.3)

In [ ]:
#XGB

from xgboost import plot_importance
from xgboost import XGBClassifier

model=XGBClassifier(booster='gbtree', 
                    colsample_bylevel=0.9, 
                    colsample_bytree=0.8, 
                    gamma=0, 
                    max_depth=4, 
                    min_child_weight=3, 
                    n_estimators=1000, 
                    nthread=4, 
                    random_state=3, 
                    learning_rate=0.05,
                    silent= True)

model.fit(X_train,y_train)
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("정확도 : ", accuracy)

정확도 :  0.713373253493014


In [ ]:
#LGBM
#https://greatjoy.tistory.com/72 참고

from lightgbm import LGBMClassifier

lgbm = LGBMClassifier(n_estimators=1000, 
                      num_leaves=150, 
                      subsample=0.8,
                      min_child_samples=3, 
                      max_depth=5)

evals = [(X_test, y_test)]
lgbm.fit(X_train, y_train, early_stopping_rounds = 100, eval_metric = 'logloss', eval_set = evals, verbose = True)

[1]	valid_0's multi_logloss: 0.886598	valid_0's multi_logloss: 0.886598
Training until validation scores don't improve for 100 rounds.
[2]	valid_0's multi_logloss: 0.86476	valid_0's multi_logloss: 0.86476
[3]	valid_0's multi_logloss: 0.846036	valid_0's multi_logloss: 0.846036
[4]	valid_0's multi_logloss: 0.830074	valid_0's multi_logloss: 0.830074
[5]	valid_0's multi_logloss: 0.81618	valid_0's multi_logloss: 0.81618
[6]	valid_0's multi_logloss: 0.804082	valid_0's multi_logloss: 0.804082
[7]	valid_0's multi_logloss: 0.793419	valid_0's multi_logloss: 0.793419
[8]	valid_0's multi_logloss: 0.784126	valid_0's multi_logloss: 0.784126
[9]	valid_0's multi_logloss: 0.775522	valid_0's multi_logloss: 0.775522
[10]	valid_0's multi_logloss: 0.767911	valid_0's multi_logloss: 0.767911
[11]	valid_0's multi_logloss: 0.761092	valid_0's multi_logloss: 0.761092
[12]	valid_0's multi_logloss: 0.754874	valid_0's multi_logloss: 0.754874
[13]	valid_0's multi_logloss: 0.749455	valid_0's multi_logloss: 0.749455
[

LGBMClassifier(max_depth=5, min_child_samples=3, n_estimators=1000,
               num_leaves=150, subsample=0.8)

In [ ]:
#LSTM

from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import EarlyStopping, ModelCheckpoint
from keras.layers import LSTM

model = Sequential()
model.add(LSTM(16, 
               input_shape=(X_train, y_train), 
               activation='relu', 
               return_sequences=False)
          )

model.add(Dense(1))

TypeError: ignored

In [ ]:
#KNN
# Preprocessing
X = excel.iloc[:, :-1].values
y = excel.iloc[:, 4].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

#Feature Scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

# Training and Predictions
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

# Evaluating the Algorithm
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 671  828  113]
 [ 604 4321  302]
 [ 213  762  536]]
              precision    recall  f1-score   support

          -1       0.45      0.42      0.43      1612
           1       0.73      0.83      0.78      5227
           2       0.56      0.35      0.44      1511

    accuracy                           0.66      8350
   macro avg       0.58      0.53      0.55      8350
weighted avg       0.65      0.66      0.65      8350



In [ ]:
#의사결정트리
from sklearn.tree import DecisionTreeClassifier

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
tree = DecisionTreeClassifier(random_state=0)
tree.fit(X_train, y_train)
print("훈련 세트 정확도: {:.3f}".format(tree.score(X_train, y_train)))
print("테스트 세트 정확도: {:.3f}".format(tree.score(X_test, y_test)))

# 트리의 깊이 제한 max_depth=n
tree = DecisionTreeClassifier(max_depth=4, random_state=0)
tree.fit(X_train, y_train)

print("훈련 세트 정확도: {:.3f}".format(tree.score(X_train, y_train)))
print("테스트 세트 정확도: {:.3f}".format(tree.score(X_test, y_test)))

훈련 세트 정확도: 1.000
테스트 세트 정확도: 0.606
훈련 세트 정확도: 0.665
테스트 세트 정확도: 0.661


In [ ]:
#랜덤포레스트
from sklearn.ensemble import RandomForestClassifier
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
forest = RandomForestClassifier(n_estimators=100, random_state=0)  # 100개 트리
forest.fit(X_train, y_train)

print("훈련 세트 정확도: {:.3f}".format(forest.score(X_train, y_train)))
print("테스트 세트 정확도: {:.3f}".format(forest.score(X_test, y_test)))

훈련 세트 정확도: 1.000
테스트 세트 정확도: 0.687


In [ ]:
#로지스틱 회귀 모델
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

lr = LogisticRegression()
lr.fit(X_train, y_train)

lr_pred = lr.predict(X_test)
print('정확도 : ', accuracy_score(y_test, lr_pred))

정확도 :  0.6300661109514228


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [ ]:
#XGB

from xgboost import plot_importance
from xgboost import XGBRegressor

model = XGBRegressor(objective='reg:squarederror')
model.fit(X_train, y_train)

pred = model.predict(X_test)
print(pred)

[1.177534   0.611214   1.0850075  ... 0.73818576 0.77096665 1.046577  ]


In [ ]:
model = XGBRegressor(n_estimators=530, learning_rate=0.005)
model.fit(X_train, y_train, verbose=False)

pred = model.predict(X_test)
print(pred)

[17:23:26] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[1.1315949  0.6004924  1.0394897  ... 0.7137525  0.7490113  0.99228394]


In [ ]:
#catboost

from catboost import CatBoostRegressor

training_data = pd.read_csv('file_to_training_data.csv')
evaluation_data = pd.read_csv('file_to_evaluation_data.csv')

training_labels = [y,y2,y3, etc.]
# establish, fit, and predict using CatBoostRegressor
cat_features = ['person_type', 'cat_example_2', etx]
model = CatBoostRegressor()
model.fit(training_data, training_labels, cat_features)
preds = model.predict(evaluation_data)

SyntaxError: ignored